# PDF OCR Processor Configuration
processing:
  max_workers: 4
  timeout_seconds: 300
  max_image_size: [2048, 2048]
  default_dpi: 200
  
ollama:
  host: "localhost:11434"
  preferred_models:
    - "llama3.2-vision:11b"
    - "llava:7b"
  
output:
  create_svg: true
  embed_images: true
  include_debug_rectangles: false
  cleanup_temp_files: true

logging:
  level: "INFO"
  log_file: "logs/pdf_ocr.log"
